# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/adv/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/adv/
Content-Type: application/json
Authorization: Token 7298a8571ed5b7bcd3af69a8c65af83ca3fa6523

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# удаление объявление пользователем, который не является создателем
DELETE {{baseUrl}}/adv/3/
Content-Type: application/json
Authorization: Token 2e3bdc388c96f36c4e8795bc46629852cb53af07

###

# попытка поменять объявление
PATCH {{baseUrl}}/adv/4/
Content-Type: application/json
Authorization: Token 7298a8571ed5b7bcd3af69a8c65af83ca3fa6523

{
  "status": "OPEN"
}

### 902ef055a9ac93f18327f1f9c45ab059f1a62c7d

# фильтрация по создателю
GET {{baseUrl}}/adv/?creator=1
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/adv/?created_at_before=2020-10-01
Content-Type: application/json

###

# фильтрация по статусу
GET {{baseUrl}}/adv/?status=CLOSED
Content-Type: application/json